# Generated by Django 5.0.1 on 2024-03-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exsets',
            name='ex_reps',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exsets',
            name='ex_weight',
            field=models.IntegerField(),
        ),
    ]
