# Generated by Django 5.0.1 on 2024-03-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0002_alter_exsets_ex_reps_alter_exsets_ex_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exsets',
            name='ex_reps',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exsets',
            name='ex_weight',
            field=models.IntegerField(null=True),
        ),
    ]
